apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  containers:
    - image: tutum/influxdb:0.9
      name: influxdb
      resources:
        requests:
          memory: 300Mi
        limits:
          memory: 300Mi
      volumeMounts:
        - name: grafana-volume
          mountPath: /data
      ports:
        - containerPort: 2003
          name: graphite-tcp
        - containerPort: 25826
          protocol: UDP
          name: collectd-udp
        - containerPort: 8086
          name: http-api
      env:
        - name: PRE_CREATE_DB
          value: production
    - image: bittrance/grafana:3.1.1-1
      name: grafana
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 100Mi
      ports:
        - containerPort: 3000
          name: http
      volumeMounts:
        - name: grafana-volume
          mountPath: /srv/grafana
        - name: grafana-config
          mountPath: /etc/grafana
  volumes:
    - name: grafana-volume
      gcePersistentDisk:
        pdName: grafana-data
        fsType: ext4
    - name: grafana-config
      configMap:
        name: grafana-config
        items:
          - key: grafana.ini
            path: grafana.ini

