apiVersion: v1
kind: Service
metadata:
  name: grafana-collectd-service
spec:
  selector:
    name: grafana
  ports:
  - port: 2003
    targetPort: graphite-tcp
  type: LoadBalancer
  loadBalancerIP: your.ip.here.plz

